cartpole1-1:
  env_id: CartPole-v1
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  alpha: 0.01
  gamma: 0.99
  hidden_dim: 10
  layer_increment: 1
  min_layers: 1
  max_layers: 1
  stop_on_reward: 500
  stop_after_episodes: 200000
  seeds: 5

cartpole1-2:
  env_id: CartPole-v1
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  alpha: 0.01
  gamma: 0.99
  hidden_dim: 10
  layer_increment: 1
  min_layers: 2
  max_layers: 2
  stop_on_reward: 500
  stop_after_episodes: 200000
  seeds: 5

cartpole1-4:
  env_id: CartPole-v1
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  alpha: 0.01
  gamma: 0.99
  hidden_dim: 10
  layer_increment: 1
  min_layers: 4
  max_layers: 4
  stop_on_reward: 500
  stop_after_episodes: 200000
  seeds: 5

cartpole1-8:
  env_id: CartPole-v1
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  alpha: 0.01
  gamma: 0.99
  hidden_dim: 10
  layer_increment: 1
  min_layers: 8
  max_layers: 8
  stop_on_reward: 500
  stop_after_episodes: 200000
  seeds: 5

cartpole1-16:
  env_id: CartPole-v1
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  alpha: 0.01
  gamma: 0.99
  hidden_dim: 10
  layer_increment: 1
  min_layers: 16
  max_layers: 16
  stop_on_reward: 500
  stop_after_episodes: 200000
  seeds: 5