cartpole1:
  env_id: CartPole-v1
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  network_sync_rate: 10
  alpha: 0.0001
  gamma: 0.99
  hidden_dim: 10
  stop_on_reward: 100000